import {StyleSheet} from 'react-native';
import {TOTAL_TAB_BAR_HEIGHT} from '../../../components/CustomTabBar/styles';
import {typography, spacing, androidTextProps} from '../../../theme/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: TOTAL_TAB_BAR_HEIGHT + spacing.lg,
  },
  pageHeader: {
    marginBottom: spacing.xxl,
    paddingHorizontal: spacing.xs,
  },
  pageTitle: {
    ...typography.h2,
    ...androidTextProps,
  },
  section: {
    borderRadius: 16,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    overflow: 'visible',
  },
  sectionLabel: {
    ...typography.bodySmall,
    fontWeight: '500',
    marginBottom: spacing.md,
    ...androidTextProps,
  },
  selectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: 12,
    minHeight: 48,
  },
  selectButtonText: {
    ...typography.body,
    fontWeight: '500',
    ...androidTextProps,
  },
  // Paid By Section (similar to CreateExpense)
  paidBySection: {
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
  },
  paidByRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  paidByText: {
    ...typography.body,
    fontWeight: '500',
    ...androidTextProps,
  },
  paidByButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: 20,
    minHeight: 36,
    justifyContent: 'center',
    gap: spacing.xs,
  },
  paidByButtonText: {
    ...typography.bodySmall,
    fontWeight: '600',
    ...androidTextProps,
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  currencyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 8,
  },
  currencyText: {
    ...typography.bodySmall,
    fontWeight: '500',
    marginRight: spacing.xs,
    ...androidTextProps,
  },
  amountInput: {
    flex: 1,
    ...typography.h2,
    paddingBottom: spacing.sm,
    borderBottomWidth: 2,
    ...androidTextProps,
  },
  // Receipt Section
  receiptArea: {
    width: '100%',
    minHeight: 120,
    borderRadius: 12,
    borderWidth: 2,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
    gap: spacing.sm,
  },
  receiptText: {
    ...typography.bodySmall,
    fontWeight: '500',
    ...androidTextProps,
  },
  receiptHint: {
    ...typography.caption,
    marginTop: spacing.xs,
    ...androidTextProps,
  },
  receiptPreviewContainer: {
    width: '100%',
    height: 120,
    borderRadius: 12,
    position: 'relative',
    overflow: 'hidden',
  },
  receiptPreview: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  receiptDocumentPreview: {
    backgroundColor: 'rgba(0,0,0,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.sm,
  },
  receiptDocumentName: {
    ...typography.caption,
    fontWeight: '500',
    maxWidth: '80%',
    ...androidTextProps,
  },
  removeReceiptButton: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Notes Section
  addNotesButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.md,
  },
  addNotesText: {
    ...typography.body,
    fontWeight: '500',
    ...androidTextProps,
  },
  notesInput: {
    minHeight: 100,
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    ...typography.body,
    textAlignVertical: 'top',
    backgroundColor: 'rgba(0,0,0,0.02)',
    ...androidTextProps,
  },
  // Action Buttons
  actionButtons: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.sm,
    marginBottom: spacing.xxxl,
  },
  cancelButton: {
    flex: 1,
    height: 50,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButtonText: {
    ...typography.button,
    fontWeight: '500',
    ...androidTextProps,
  },
  saveButton: {
    flex: 1,
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#FFFFFF',
    ...typography.button,
    fontWeight: '500',
    ...androidTextProps,
  },
});
