import {StyleSheet, Platform} from 'react-native';
import {typography, spacing, androidTextProps} from '../../../theme/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  keyboardView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: spacing.lg,
    paddingBottom: spacing.lg,
  },
  card: {
    marginHorizontal: spacing.lg,
    borderRadius: 16,
    padding: spacing.lg,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  statusSection: {
    alignItems: 'center',
    marginBottom: spacing.xxl,
  },
  statusTitle: {
    ...typography.h3,
    fontWeight: '700',
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
    textAlign: 'center',
    ...androidTextProps,
  },
  statusDescription: {
    ...typography.bodySmall,
    textAlign: 'center',
    ...androidTextProps,
  },
  backupCodeSection: {
    marginBottom: spacing.xxl,
    padding: spacing.lg,
    borderRadius: 12,
    borderWidth: 2,
    alignItems: 'center',
  },
  backupCodeTitle: {
    ...typography.body,
    fontWeight: '700',
    marginBottom: spacing.md,
    ...androidTextProps,
  },
  backupCode: {
    ...typography.h2,
    fontWeight: '700',
    letterSpacing: 2,
    marginBottom: spacing.md,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    ...androidTextProps,
  },
  backupCodeHint: {
    ...typography.caption,
    textAlign: 'center',
    marginBottom: spacing.lg,
    ...androidTextProps,
  },
  dismissButton: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: 8,
  },
  dismissButtonText: {
    ...typography.bodySmall,
    fontWeight: '600',
    color: '#FFFFFF',
    ...androidTextProps,
  },
  enableButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    gap: spacing.sm,
  },
  enableButtonText: {
    ...typography.button,
    color: '#FFFFFF',
    ...androidTextProps,
  },
  disableButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    borderWidth: 1.5,
    gap: spacing.sm,
  },
  disableButtonText: {
    ...typography.button,
    ...androidTextProps,
  },
  infoCard: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    padding: spacing.lg,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  infoText: {
    flex: 1,
    ...typography.bodySmall,
    ...androidTextProps,
  },
  qrCodeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xxl,
    padding: spacing.lg,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    alignSelf: 'center',
  },
  qrCode: {
    width: 250,
    height: 250,
  },
  manualEntrySection: {
    padding: spacing.lg,
    borderRadius: 12,
    marginBottom: spacing.xxl,
    alignItems: 'center',
  },
  manualEntryTitle: {
    ...typography.bodySmall,
    marginBottom: spacing.sm,
    textAlign: 'center',
    ...androidTextProps,
  },
  manualEntryCode: {
    ...typography.medium,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    letterSpacing: 2,
    ...androidTextProps,
  },
  inputSection: {
    marginBottom: spacing.xxl,
  },
  codeInput: {
    width: '100%',
    height: 56,
    borderWidth: 1.5,
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    ...typography.h2,
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 8,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    ...androidTextProps,
  },
  primaryButton: {
    width: '100%',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  primaryButtonText: {
    ...typography.button,
    color: '#FFFFFF',
    ...androidTextProps,
  },
  cancelButton: {
    width: '100%',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    ...typography.button,
    fontWeight: '500',
    ...androidTextProps,
  },
  backupCodesContainer: {
    marginBottom: spacing.xxl,
    padding: spacing.lg,
    borderRadius: 12,
    gap: spacing.md,
  },
  backupCodeItem: {
    padding: spacing.md,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
  },
  backupCodeText: {
    ...typography.body,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    letterSpacing: 1,
    ...androidTextProps,
  },
});
