require Pod::Executable.execute_command(
  'node',
  ['-p', 'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})', __dir__]
).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'clevrcash' do
  config = use_native_modules!

  # Static frameworks (required for Firebase)
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )
end

post_install do |installer|
  # Standard RN post install
  react_native_post_install(
    installer,
    '../node_modules/react-native',
    :mac_catalyst_enabled => false
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end

  
end
