import {StyleSheet} from 'react-native';
import {typography, spacing, androidTextProps} from '../../../theme/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: 100,
  },
  pageHeader: {
    marginBottom: spacing.xxl,
    paddingHorizontal: spacing.xs,
  },
  pageTitle: {
    ...typography.h1,
    ...androidTextProps,
  },
  section: {
    borderRadius: 16,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    zIndex: 1,
    overflow: 'visible',
  },
  sectionLabel: {
    ...typography.bodySmall,
    fontWeight: '500',
    marginBottom: spacing.md,
    ...androidTextProps,
  },
  // Participants Section - Higher z-index to ensure search results appear above
  participantsSection: {
    zIndex: 1000,
    elevation: 5,
  },
  // Participants Section
  searchContainer: {
    position: 'relative',
    marginBottom: spacing.md,
    zIndex: 9999,
    elevation: 10,
    overflow: 'visible',
  },
  searchInput: {
    height: 48,
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    ...typography.body,
    ...androidTextProps,
  },
  searchResults: {
    position: 'absolute',
    top: 52,
    left: 0,
    right: 0,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
    maxHeight: 200,
    zIndex: 99999,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 20,
  },
  searchResultItem: {
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems:'center',
  },
  searchResultText: {
    ...typography.body,
    fontWeight: '500',
    marginBottom: spacing.xs,
    ...androidTextProps,
  },
  searchResultEmail: {
    ...typography.bodySmall,
    ...androidTextProps,
  },
  availableFriendsContainer: {
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.1)',
  },
  availableFriendsLabel: {
    ...typography.bodySmall,
    fontWeight: '500',
    marginBottom: spacing.sm,
    ...androidTextProps,
  },
  friendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.md,
    borderRadius: 8,
    marginBottom: spacing.xs,
    backgroundColor: 'rgba(0,0,0,0.02)',
  },
  friendItemText: {
    ...typography.body,
    fontWeight: '500',
    ...androidTextProps,
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: 24,
    minHeight: 36,
  },
  chipText: {
    ...typography.bodySmall,
    fontWeight: '500',
    marginRight: spacing.xs,
    ...androidTextProps,
  },
  chipRemove: {
    marginLeft: 4,
  },
  // Expense Details
  expenseDetailsRow: {
    flexDirection: 'row',
    gap: 12,
    zIndex: 1,
  },
  receiptArea: {
    width: 100,
    height: 100,
    borderRadius: 12,
    borderWidth: 2,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.6,
  },
  receiptText: {
    ...typography.caption,
    marginTop: spacing.sm,
    ...androidTextProps,
  },
  receiptPreviewContainer: {
    zIndex: 1,
    width: 100,
    height: 100,
    borderRadius: 12,
    position: 'relative',
    overflow: 'hidden',
  },
  receiptPreview: {
    width: 100,
    height: 100,
    borderRadius: 12,
    resizeMode: 'cover',
  },
  receiptDocumentPreview: {
    backgroundColor: 'rgba(0,0,0,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  receiptDocumentName: {
    ...typography.captionSmall,
    marginTop: spacing.xs,
    textAlign: 'center',
    ...androidTextProps,
  },
  removeReceiptButton: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  expenseInputs: {
    flex: 1,
    gap: spacing.md,
  },
  descriptionInput: {
    ...typography.medium,
    paddingBottom: spacing.sm,
    borderBottomWidth: 2,
    ...androidTextProps,
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  currencyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 8,
  },
  currencyText: {
    ...typography.bodySmall,
    fontWeight: '500',
    marginRight: spacing.xs,
    ...androidTextProps,
  },
  amountInput: {
    flex: 1,
    ...typography.h2,
    paddingBottom: spacing.sm,
    borderBottomWidth: 2,
    ...androidTextProps,
  },
  // Paid By Section
  paidBySection: {
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
  },
  paidByRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  paidByText: {
    ...typography.body,
    fontWeight: '500',
    ...androidTextProps,
  },
  paidByButton: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: 20,
    minHeight: 36,
    justifyContent: 'center',
  },
  paidByButtonText: {
    color: '#FFFFFF',
    ...typography.bodySmall,
    fontWeight: '600',
    ...androidTextProps,
  },
  splitPerPerson: {
    ...typography.bodySmall,
    marginTop: spacing.sm,
    fontWeight: '400',
    ...androidTextProps,
  },
  // Split Details
  splitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  splitRowName: {
    ...typography.body,
    fontWeight: '500',
    flex: 1,
    ...androidTextProps,
  },
  splitInput: {
    width: 120,
    height: 40,
    borderRadius: 8,
    paddingHorizontal: spacing.md,
    ...typography.body,
    textAlign: 'right',
    ...androidTextProps,
  },
  // Reimbursement
  reimbursementSelect: {
    gap: 8,
  },
  reimbursementOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 12,
    marginBottom: 8,
  },
  reimbursementOptionText: {
    ...typography.body,
    fontWeight: '500',
    ...androidTextProps,
  },
  // Itemized
  itemizedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  addItemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  addItemText: {
    color: '#FFFFFF',
    ...typography.bodySmall,
    fontWeight: '600',
    ...androidTextProps,
  },
  itemsList: {
    gap: 12,
  },
  itemCard: {
    padding: 16,
    borderRadius: 12,
    marginBottom: 8,
  },
  itemRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
    alignItems: 'center',
  },
  itemNameInput: {
    flex: 2,
    height: 40,
    borderRadius: 8,
    paddingHorizontal: spacing.md,
    ...typography.body,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
    ...androidTextProps,
  },
  itemAmountInput: {
    flex: 1,
    height: 40,
    borderRadius: 8,
    paddingHorizontal: spacing.md,
    ...typography.body,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
    textAlign: 'right',
    ...androidTextProps,
  },
  itemQuantityInput: {
    width: 80,
    height: 40,
    borderRadius: 8,
    paddingHorizontal: spacing.md,
    ...typography.body,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
    ...androidTextProps,
  },
  removeItemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginLeft: 'auto',
  },
  removeItemText: {
    ...typography.bodySmall,
    fontWeight: '500',
    ...androidTextProps,
  },
  emptyText: {
    ...typography.bodySmall,
    textAlign: 'center',
    paddingVertical: spacing.xxl,
    ...androidTextProps,
  },
  // Date and Category
  dateCategoryRow: {
    flexDirection: 'row',
    gap: 12,
  },
  dateContainer: {
    flex: 1,
  },
  fieldLabel: {
    ...typography.bodySmall,
    fontWeight: '500',
    marginBottom: spacing.sm,
    ...androidTextProps,
  },
  dateInput: {
    height: 48,
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    ...typography.body,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...androidTextProps,
  },
  dateText: {
    ...typography.body,
    ...androidTextProps,
  },
  datePickerContainer: {
    marginBottom: spacing.lg,
  },
  datePickerInput: {
    height: 48,
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    ...typography.body,
    marginBottom: spacing.md,
    backgroundColor: 'rgba(0,0,0,0.05)',
    ...androidTextProps,
  },
  quickDateButtons: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  quickDateButton: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickDateText: {
    ...typography.bodySmall,
    fontWeight: '600',
    ...androidTextProps,
  },
  categoryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    borderWidth: 1,
    gap: spacing.sm,
  },
  categoryButtonText: {
    ...typography.body,
    ...androidTextProps,
  },
  // Notes
  addNotesButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 8,
    borderWidth: 1,
  },
  addNotesText: {
    ...typography.body,
    fontWeight: '500',
    ...androidTextProps,
  },
  notesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  notesInput: {
    minHeight: 80,
    borderRadius: 12,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    ...typography.body,
    borderWidth: 0.1,
    textAlignVertical: 'top',
    ...androidTextProps,
  },
  // Action Buttons
  actionButtons: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.sm,
    marginBottom: spacing.xxxl,
  },
  cancelButton: {
    flex: 1,
    height: 50,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButtonText: {
    ...typography.button,
    fontWeight: '500',
    ...androidTextProps,
  },
  saveButton: {
    flex: 1,
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#FFFFFF',
    ...typography.button,
    fontWeight: '500',
    ...androidTextProps,
  },
  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: spacing.xxl,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  modalTitle: {
    ...typography.h3,
    marginBottom: spacing.lg,
    ...androidTextProps,
  },
  modalScroll: {
    maxHeight: 400,
  },
  modalOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.lg,
    borderRadius: 12,
    marginBottom: spacing.sm,
  },
  modalOptionText: {
    ...typography.body,
    fontWeight: '500',
    ...androidTextProps,
  },
  modalOptionDesc: {
    ...typography.bodySmall,
    marginTop: spacing.xs,
    ...androidTextProps,
  },
  modalCloseButton: {
    marginTop: spacing.lg,
    paddingVertical: spacing.lg,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  modalCloseText: {
    ...typography.button,
    ...androidTextProps,
  },
});
